# SPDX-License-Identifier: MIT

param(
    [string]$OutputPath,
    [switch]$Check,
    [switch]$Deploy,
    [string]$DeployDirectory,
    [switch]$Validation
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

if ($Check -and $Deploy) {
    throw '-Check and -Deploy cannot be used together.'
}
if ($DeployDirectory -and -not $Deploy) {
    throw '-DeployDirectory requires -Deploy.'
}

$repoRoot = Split-Path -Parent $PSScriptRoot
$runtimeName = if ($Validation) { 'ubermensch_validation.lua' } else { 'ubermensch.lua' }
if (-not $OutputPath) {
    $OutputPath = Join-Path $repoRoot $runtimeName
}
$sourceRoot = Join-Path $repoRoot 'src\ubermensch'
$validationRoot = Join-Path $repoRoot 'tools\validation'
$licensePath = Join-Path $repoRoot 'LICENSE'
$moduleDescriptors = [System.Collections.Generic.List[object]]::new()
foreach ($moduleFile in @(Get-ChildItem -LiteralPath $sourceRoot -Filter '*.lua' -File | Sort-Object Name)) {
    $moduleDescriptors.Add([pscustomobject]@{
        Name = 'ubermensch.' + $moduleFile.BaseName
        Path = $moduleFile.FullName
    })
}
if ($Validation) {
    if (-not (Test-Path -LiteralPath $validationRoot -PathType Container)) {
        throw "Validation modules not found: $validationRoot"
    }
    foreach ($moduleFile in @(Get-ChildItem -LiteralPath $validationRoot -Filter '*.lua' -File | Sort-Object Name)) {
        $moduleDescriptors.Add([pscustomobject]@{
            Name = 'validation.' + $moduleFile.BaseName
            Path = $moduleFile.FullName
        })
    }
}
if ($moduleDescriptors.Count -eq 0) {
    throw "No runtime modules found in $sourceRoot"
}
if (-not (Test-Path -LiteralPath $licensePath -PathType Leaf)) {
    throw "License file not found: $licensePath"
}

$lineFeed = "`n"
$parts = [System.Collections.Generic.List[string]]::new()
$parts.Add('-- SPDX-License-Identifier: MIT')
$parts.Add('--[[')
foreach ($licenseLine in [System.IO.File]::ReadAllLines($licensePath, [System.Text.Encoding]::UTF8)) {
    $parts.Add($licenseLine)
}
$parts.Add(']]')
$parts.Add('')
$parts.Add($(if ($Validation) { '-- Ubermensch LMAOBox Match Validation Runtime' } else { '-- Ubermensch LMAOBox' }))
$parts.Add('-- Generated by tools/build_runtime.ps1; edit authored modules instead.')
$parts.Add('')
$parts.Add('local module_loaders = {}')
$parts.Add('local loaded_modules = {}')
$parts.Add('')
$parts.Add('local function require(name)')
$parts.Add('    if loaded_modules[name] ~= nil then')
$parts.Add('        return loaded_modules[name]')
$parts.Add('    end')
$parts.Add('    local loader = module_loaders[name]')
$parts.Add('    if loader == nil then')
$parts.Add('        error("module not bundled: " .. tostring(name), 2)')
$parts.Add('    end')
$parts.Add('    local module = loader()')
$parts.Add('    loaded_modules[name] = module')
$parts.Add('    return module')
$parts.Add('end')
$parts.Add('')

foreach ($moduleDescriptor in $moduleDescriptors) {
    $path = $moduleDescriptor.Path
    $moduleName = $moduleDescriptor.Name
    $source = [System.IO.File]::ReadAllText($path).Replace("`r`n", "`n")
    if ($source -match '[^\x00-\x7F]') {
        throw "Runtime module is not ASCII-only: $path"
    }
    $parts.Add('module_loaders["' + $moduleName + '"] = function()')
    $parts.Add($source.TrimEnd("`r", "`n"))
    $parts.Add('end')
    $parts.Add('')
}

$hostLines = @(
    '    entities = entities,',
    '    client = client,',
    '    globals = globals,',
    '    engine = engine,',
    '    gamerules = gamerules,',
    '    draw = draw,',
    '    gui = gui,',
    '    input = input,',
    '    callbacks = callbacks,',
    '    filesystem = filesystem,',
    '    mouse_left = MOUSE_LEFT,',
    '    frame_net_update_end = E_ClientFrameStage',
    '        and E_ClientFrameStage.FRAME_NET_UPDATE_END',
    '        or FRAME_NET_UPDATE_END,',
    '    frame_render_start = E_ClientFrameStage',
    '        and E_ClientFrameStage.FRAME_RENDER_START',
    '        or FRAME_RENDER_START,',
    '    file_api = io,',
    '    os_api = os,',
    '    print = print,'
)
if ($Validation) {
    $parts.Add('local validation_host = {')
    foreach ($hostLine in $hostLines) { $parts.Add($hostLine) }
    $parts.Add('    key_f8 = E_ButtonCode and E_ButtonCode.KEY_F8 or KEY_F8 or 99,')
    $parts.Add('    lua_version = _VERSION,')
    $parts.Add('}')
    $parts.Add('local validation_recorder = require("validation.recorder").new(validation_host)')
    $parts.Add('local validation_app = require("ubermensch.app").start(validation_host, {')
    $parts.Add('    observer = validation_recorder,')
    $parts.Add('    adapter_diagnostics = true,')
    $parts.Add('})')
    $parts.Add('if validation_app == nil then')
    $parts.Add('    validation_recorder:close("application_start_failed")')
    $parts.Add('end')
} else {
    $parts.Add('require("ubermensch.app").start({')
    foreach ($hostLine in $hostLines) { $parts.Add($hostLine) }
    $parts.Add('})')
}
$parts.Add('')

$output = [string]::Join($lineFeed, $parts)
$normalizedOutput = $output.Replace("`r`n", "`n")

if ($Check) {
    if (-not (Test-Path -LiteralPath $OutputPath -PathType Leaf)) {
        throw "Generated runtime is missing: $OutputPath"
    }
    $current = [System.IO.File]::ReadAllText($OutputPath).Replace("`r`n", "`n")
    if ($current -cne $normalizedOutput) {
        throw 'Generated runtime is stale; run tools/build_runtime.ps1'
    }
    Write-Output "PASS: generated runtime is current: $OutputPath"
    exit 0
}

$encoding = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($OutputPath, $normalizedOutput, $encoding)
Write-Output "Generated: $OutputPath"

if ($Deploy) {
    if (-not $DeployDirectory) {
        $localAppData = [Environment]::GetFolderPath(
            [Environment+SpecialFolder]::LocalApplicationData
        )
        if (-not $localAppData) {
            throw 'Cannot resolve the LocalAppData directory for deployment.'
        }
        $DeployDirectory = Join-Path $localAppData 'lua'
    }

    $outputFullPath = [System.IO.Path]::GetFullPath($OutputPath)
    $deployFullPath = [System.IO.Path]::GetFullPath(
        (Join-Path $DeployDirectory $runtimeName)
    )
    if ([string]::Equals(
        $outputFullPath,
        $deployFullPath,
        [StringComparison]::OrdinalIgnoreCase
    )) {
        Write-Output "Deployed: $deployFullPath (already the generated output)"
        exit 0
    }

    [System.IO.Directory]::CreateDirectory($DeployDirectory) | Out-Null
    if (Test-Path -LiteralPath $deployFullPath) {
        Remove-Item -LiteralPath $deployFullPath -Force
    }
    Copy-Item -LiteralPath $outputFullPath -Destination $deployFullPath
    Write-Output "Deployed: $deployFullPath"
}
